// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVPiM6zR54n_IKXKeST5OaM3_6d3fvlQ',
    appId: '1:729178992675:web:dfe1f974df98c2b7a60196',
    messagingSenderId: '729178992675',
    projectId: 'afriqueen-e0b18',
    authDomain: 'afriqueen-e0b18.firebaseapp.com',
    storageBucket: 'afriqueen-e0b18.firebasestorage.app',
    measurementId: 'G-Z25X0P7C9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOyAinTew7da7UVhsGr1APW7Hb8qYAsc',
    appId: '1:729178992675:android:192a9f4f3fbaa74aa60196',
    messagingSenderId: '729178992675',
    projectId: 'afriqueen-e0b18',
    storageBucket: 'afriqueen-e0b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJj0uAA-sV7ejbS13EK92WCE2wnRiLSD4',
    appId: '1:729178992675:ios:972b382d4935c8c6a60196',
    messagingSenderId: '729178992675',
    projectId: 'afriqueen-e0b18',
    storageBucket: 'afriqueen-e0b18.firebasestorage.app',
    iosBundleId: 'com.example.afriqueen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJj0uAA-sV7ejbS13EK92WCE2wnRiLSD4',
    appId: '1:729178992675:ios:972b382d4935c8c6a60196',
    messagingSenderId: '729178992675',
    projectId: 'afriqueen-e0b18',
    storageBucket: 'afriqueen-e0b18.firebasestorage.app',
    iosBundleId: 'com.example.afriqueen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVPiM6zR54n_IKXKeST5OaM3_6d3fvlQ',
    appId: '1:729178992675:web:76b5511ef01aa5aba60196',
    messagingSenderId: '729178992675',
    projectId: 'afriqueen-e0b18',
    authDomain: 'afriqueen-e0b18.firebaseapp.com',
    storageBucket: 'afriqueen-e0b18.firebasestorage.app',
    measurementId: 'G-7PB9VLHJ06',
  );
}
