// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVPiM6zR54n_IKXKeST5OaM3_6d3fvlQ',
    appId: '1:426919301496:web:dfe1f974df98c2b7a60196',
    messagingSenderId: '426919301496',
    projectId: 'afriqeen-bcd27',
    authDomain: 'afriqeen-bcd27.firebaseapp.com',
    storageBucket: 'afriqeen-bcd27.firebasestorage.app',
    measurementId: 'G-Z25X0P7C9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_J5BloVOPPnyqJ6QgDvgYj9L26YbhSo',
    appId: '1:426919301496:android:c42078ee7c5135f8bcf88d',
    messagingSenderId: '426919301496',
    projectId: 'afriqeen-bcd27',
    storageBucket: 'afriqeen-bcd27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltPWIfGs2673Uz45RSW6rtNubmYb8dGA',
    appId: '1:426919301496:ios:2185019e1b50a7afbcf88d',
    messagingSenderId: '426919301496',
    projectId: 'afriqeen-bcd27',
    storageBucket: 'afriqeen-bcd27.firebasestorage.app',
    iosBundleId: 'com.company.afriqueen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltPWIfGs2673Uz45RSW6rtNubmYb8dGA',
    appId: '1:426919301496:ios:972b382d4935c8c6a60196',
    messagingSenderId: '426919301496',
    projectId: 'afriqeen-bcd27',
    storageBucket: 'afriqeen-bcd27.firebasestorage.app',
    iosBundleId: 'com.company.afriqueen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVPiM6zR54n_IKXKeST5OaM3_6d3fvlQ',
    appId: '1:426919301496:web:76b5511ef01aa5aba60196',
    messagingSenderId: '426919301496',
    projectId: 'afriqeen-bcd27',
    authDomain: 'afriqeen-bcd27.firebaseapp.com',
    storageBucket: 'afriqeen-bcd27.firebasestorage.app',
    measurementId: 'G-7PB9VLHJ06',
  );
}
